# Site settings
title: Rish.io
description: > # this means to ignore newlines until "baseurl:"
  I am Rish, I make things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rish.io" # the base hostname & protocol for your site
github_username: rish

# Build settings
markdown: kramdown
